-- MySQL Script generated by MySQL Workbench
-- Sun May 14 19:52:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
grant all privileges on storageprogetto.* to 'root'@'localhost';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema storageprogetto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storageprogetto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storageprogetto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `storageprogetto` ;

-- -----------------------------------------------------
-- Table `storageprogetto`.`amministratore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storageprogetto`.`amministratore` (
  `idamministratore` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `foto` BLOB NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idamministratore`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `storageprogetto`.`prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storageprogetto`.`prodotto` (
  `idProdotto` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `descrizione` TEXT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProdotto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `storageprogetto`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storageprogetto`.`utente` (
  `idutente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `foto` BLOB NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  `indirizzo` VARCHAR(45) NULL DEFAULT NULL,
  `cap` VARCHAR(45) NULL DEFAULT NULL,
  `metodo di pagamento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idutente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
